import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import AdbIcon from '@mui/icons-material/Adb';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Walli</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/">Walli</a>
        </h1>

        <p className={styles.description}>
          Download Best In Class Wallpaper, Uploaded Daily
        </p>

        <div className={styles.grid}>
          <a href="/nature" className={styles.nature}>
            <h2>Nature &rarr;</h2>
          </a>

          <a href="/cities" className={styles.SkyScrappers}>
            <h2>SkyScrappers &rarr;</h2>
          </a>

          <a href="/arts" className={styles.Abstract}>
            <h2>Abstract &rarr;</h2>
          </a>

          <a href="/colors" className={styles.Games}>
            <h2>Games &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        Walli
        <AdbIcon sx={{ display: { xs: 'flex', md: 'flex' }, mr: 1 }} />
      </footer>
    </div>
  )
}
